name: Bug Report
description: Report a bug
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
  - type: textarea
    attributes:
      label: Steps to Reproduce
  - type: textarea
    attributes:
      label: Expected Behavior
