name: Feature Request
description: Request a feature
title: "[FEATURE]: "
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: Description
  - type: textarea
    attributes:
      label: Acceptance Criteria
